name = "image-site-job-worker"
main = "functions/_worker.js"
compatibility_date = "2026-05-11"

[[durable_objects.bindings]]
name = "IMAGE_SITE_JOB_STORE"
class_name = "JobStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["JobStore"]

[[kv_namespaces]]
binding = "IMAGE_SITE_JOBS"
id = "70a6caec5b3642709626007581c5921f"

[[queues.consumers]]
queue = "image-site-jobs"
max_batch_size = 1
max_batch_timeout = 1
